[package]
name = "world_generator_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
rand = "0.7"
worldgen = " 0.5.3"

[[bin]]
name = "world_generator_3d"
target = "src/main.rs"